---
# 官方文档与 GitHub 仓库
- 文档资源:
    - Homepage:
        - abbr: HP
          href: https://github.com/gethomepage/homepage
          description: GitHub 仓库

    - Caddy:
        - abbr: CD
          href: https://caddyserver.com/docs/
          description: 官方文档

    - Flatnotes:
        - abbr: FN
          href: https://github.com/dullage/flatnotes
          description: GitHub 仓库

    - Alist:
        - abbr: AL
          href: https://github.com/alist-org/alist
          description: GitHub 仓库